using MMO.ContentStudio.AuthoringHost.Health;

namespace MMO.ContentStudio.AuthoringHost.Features.Mobs;

public sealed class MobSchemaRequirements : IAuthoringSchemaRequirementProvider
{
    public string FeatureId => "prototype-mob-authoring-v1";

    public IReadOnlyList<AuthoringSchemaRequirement> GetRequirements() =>
    [
        AuthoringSchemaRequirement.Table("mob_factions"),
        AuthoringSchemaRequirement.Table("mob_faction_dispositions"),
        AuthoringSchemaRequirement.Table("mob_definitions"),
        AuthoringSchemaRequirement.Table("mob_combat_profiles"),
        AuthoringSchemaRequirement.Table("mob_combat_bonuses"),
        AuthoringSchemaRequirement.Table("mob_drops"),
        AuthoringSchemaRequirement.Column("mob_factions", "faction_id"),
        AuthoringSchemaRequirement.Column("mob_factions", "display_name"),
        AuthoringSchemaRequirement.Column("mob_factions", "description"),
        AuthoringSchemaRequirement.Column("mob_factions", "updated_at"),
        AuthoringSchemaRequirement.Column("mob_faction_dispositions", "source_faction_id"),
        AuthoringSchemaRequirement.Column("mob_faction_dispositions", "target_faction_id"),
        AuthoringSchemaRequirement.Column("mob_faction_dispositions", "disposition"),
        AuthoringSchemaRequirement.Column("mob_faction_dispositions", "updated_at"),
        AuthoringSchemaRequirement.Column("mob_definitions", "mob_definition_id"),
        AuthoringSchemaRequirement.Column("mob_definitions", "display_name"),
        AuthoringSchemaRequirement.Column("mob_definitions", "publication_state"),
        AuthoringSchemaRequirement.Column("mob_definitions", "visual_texture_path"),
        AuthoringSchemaRequirement.Column("mob_definitions", "source_width"),
        AuthoringSchemaRequirement.Column("mob_definitions", "source_height"),
        AuthoringSchemaRequirement.Column("mob_definitions", "visual_anchor_offset_x"),
        AuthoringSchemaRequirement.Column("mob_definitions", "visual_anchor_offset_y"),
        AuthoringSchemaRequirement.Column("mob_definitions", "visual_render_scale"),
        AuthoringSchemaRequirement.Column("mob_definitions", "footprint_width_tiles"),
        AuthoringSchemaRequirement.Column("mob_definitions", "footprint_height_tiles"),
        AuthoringSchemaRequirement.Column("mob_definitions", "max_health"),
        AuthoringSchemaRequirement.Column("mob_definitions", "movement_speed_tiles_per_second"),
        AuthoringSchemaRequirement.Column("mob_definitions", "defeated_hold_duration_ms"),
        AuthoringSchemaRequirement.Column("mob_definitions", "respawn_delay_ms"),
        AuthoringSchemaRequirement.Column("mob_definitions", "combat_faction_id"),
        AuthoringSchemaRequirement.Column("mob_definitions", "can_proactively_target_hostile_mobs"),
        AuthoringSchemaRequirement.Column("mob_definitions", "mob_detection_radius_tiles"),
        AuthoringSchemaRequirement.Column("mob_definitions", "mob_target_scan_interval_ms"),
        AuthoringSchemaRequirement.Column("mob_definitions", "mob_target_scan_candidate_limit"),
        AuthoringSchemaRequirement.Column("mob_definitions", "created_at"),
        AuthoringSchemaRequirement.Column("mob_definitions", "updated_at"),
        AuthoringSchemaRequirement.Column("mob_combat_profiles", "mob_definition_id"),
        AuthoringSchemaRequirement.Column("mob_combat_profiles", "attack_type"),
        AuthoringSchemaRequirement.Column("mob_combat_profiles", "accuracy_style"),
        AuthoringSchemaRequirement.Column("mob_combat_profiles", "minimum_range_tiles"),
        AuthoringSchemaRequirement.Column("mob_combat_profiles", "maximum_range_tiles"),
        AuthoringSchemaRequirement.Column("mob_combat_profiles", "attack_speed_units"),
        AuthoringSchemaRequirement.Column("mob_combat_profiles", "attack_level"),
        AuthoringSchemaRequirement.Column("mob_combat_profiles", "strength_level"),
        AuthoringSchemaRequirement.Column("mob_combat_profiles", "defence_level"),
        AuthoringSchemaRequirement.Column("mob_combat_profiles", "updated_at"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "attack_thrust"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "attack_slash"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "attack_crush"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "attack_ranged"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "attack_magic"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "strength_melee"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "strength_ranged"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "strength_magic"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "defence_thrust"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "defence_slash"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "defence_crush"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "defence_ranged"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "defence_magic"),
        AuthoringSchemaRequirement.Column("mob_combat_bonuses", "updated_at"),
        AuthoringSchemaRequirement.Column("mob_drops", "mob_definition_id"),
        AuthoringSchemaRequirement.Column("mob_drops", "drop_order"),
        AuthoringSchemaRequirement.Column("mob_drops", "item_id"),
        AuthoringSchemaRequirement.Column("mob_drops", "stack_count"),
        AuthoringSchemaRequirement.Column("mob_drops", "updated_at"),
        AuthoringSchemaRequirement.Constraint("mob_factions_faction_id_format_check"),
        AuthoringSchemaRequirement.Constraint("mob_factions_display_name_nonblank_check"),
        AuthoringSchemaRequirement.Constraint("mob_faction_dispositions_no_self_check"),
        AuthoringSchemaRequirement.Constraint("mob_faction_dispositions_disposition_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_id_format_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_display_name_nonblank_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_publication_state_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_visual_texture_path_nonblank_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_source_dimensions_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_visual_numbers_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_footprint_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_max_health_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_movement_speed_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_lifecycle_durations_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_target_scan_values_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_proactive_targeting_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_timestamp_order_check"),
        AuthoringSchemaRequirement.Constraint("mob_combat_profiles_attack_type_check"),
        AuthoringSchemaRequirement.Constraint("mob_combat_profiles_accuracy_style_check"),
        AuthoringSchemaRequirement.Constraint("mob_combat_profiles_attack_type_accuracy_style_check"),
        AuthoringSchemaRequirement.Constraint("mob_combat_profiles_range_check"),
        AuthoringSchemaRequirement.Constraint("mob_combat_profiles_attack_speed_units_check"),
        AuthoringSchemaRequirement.Constraint("mob_combat_profiles_level_bounds_check"),
        AuthoringSchemaRequirement.Constraint("mob_drops_drop_order_check"),
        AuthoringSchemaRequirement.Constraint("mob_drops_stack_count_check"),
        AuthoringSchemaRequirement.Constraint("mob_drops_unique_item_per_mob")
    ];
}
