using MMO.ContentStudio.AuthoringHost.Health;

namespace MMO.ContentStudio.AuthoringHost.Features.Items;

public sealed class ItemSchemaRequirements : IAuthoringSchemaRequirementProvider
{
    public string FeatureId => "items";

    public IReadOnlyList<AuthoringSchemaRequirement> GetRequirements() =>
    [
        AuthoringSchemaRequirement.Table("item_definitions"),
        AuthoringSchemaRequirement.Table("character_inventory"),
        AuthoringSchemaRequirement.Table("character_equipment"),
        AuthoringSchemaRequirement.Table("ground_items"),
        AuthoringSchemaRequirement.Table("equipment_slot_definitions"),
        AuthoringSchemaRequirement.Table("skill_definitions"),
        AuthoringSchemaRequirement.Table("item_consumable_profiles"),
        AuthoringSchemaRequirement.Table("item_consumable_requirements"),
        AuthoringSchemaRequirement.Table("item_consumable_effects"),
        AuthoringSchemaRequirement.Table("item_skill_requirements"),
        AuthoringSchemaRequirement.Table("item_skill_modifiers"),
        AuthoringSchemaRequirement.Table("item_combat_profiles"),
        AuthoringSchemaRequirement.Table("item_combat_bonuses"),
        AuthoringSchemaRequirement.Table("item_tool_capabilities"),
        AuthoringSchemaRequirement.Table("item_equipped_visuals"),
        AuthoringSchemaRequirement.Table("item_equipped_visual_pose_anchors"),
        AuthoringSchemaRequirement.Column("item_definitions", "item_id"),
        AuthoringSchemaRequirement.Column("item_definitions", "item_name"),
        AuthoringSchemaRequirement.Column("item_definitions", "icon_texture_path"),
        AuthoringSchemaRequirement.Column("item_definitions", "equipment_slot_id"),
        AuthoringSchemaRequirement.Column("item_definitions", "runtime_enabled"),
        AuthoringSchemaRequirement.Column("item_definitions", "required_strength"),
        AuthoringSchemaRequirement.Column("item_definitions", "reference_value"),
        AuthoringSchemaRequirement.Column("item_definitions", "trade_policy"),
        AuthoringSchemaRequirement.Column("item_definitions", "death_behavior"),
        AuthoringSchemaRequirement.Column("item_definitions", "death_transform_item_id"),
        AuthoringSchemaRequirement.Column("item_definitions", "shop_policy"),
        AuthoringSchemaRequirement.Column("item_definitions", "npc_buy_price"),
        AuthoringSchemaRequirement.Column("item_definitions", "npc_sell_price"),
        AuthoringSchemaRequirement.Column("item_definitions", "reclaim_policy"),
        AuthoringSchemaRequirement.Column("item_definitions", "reclaim_value"),
        AuthoringSchemaRequirement.Column("item_definitions", "condition_policy_id"),
        AuthoringSchemaRequirement.Column("item_definitions", "repair_policy_id"),
        AuthoringSchemaRequirement.Column("item_definitions", "updated_at"),
        AuthoringSchemaRequirement.Column("equipment_slot_definitions", "slot_id"),
        AuthoringSchemaRequirement.Column("equipment_slot_definitions", "display_name"),
        AuthoringSchemaRequirement.Column("equipment_slot_definitions", "sort_order"),
        AuthoringSchemaRequirement.Column("skill_definitions", "skill_id"),
        AuthoringSchemaRequirement.Column("skill_definitions", "display_name"),
        AuthoringSchemaRequirement.Column("skill_definitions", "category"),
        AuthoringSchemaRequirement.Column("skill_definitions", "sort_order"),
        AuthoringSchemaRequirement.Column("item_consumable_profiles", "use_action"),
        AuthoringSchemaRequirement.Column("item_consumable_profiles", "consume_quantity"),
        AuthoringSchemaRequirement.Column("item_consumable_profiles", "result_item_id"),
        AuthoringSchemaRequirement.Column("item_consumable_profiles", "success_message"),
        AuthoringSchemaRequirement.Column("item_consumable_profiles", "usable_in_combat"),
        AuthoringSchemaRequirement.Column("item_consumable_profiles", "cooldown_ms"),
        AuthoringSchemaRequirement.Column("item_consumable_profiles", "use_animation_id"),
        AuthoringSchemaRequirement.Column("item_consumable_profiles", "use_sound_resource_path"),
        AuthoringSchemaRequirement.Column("item_consumable_profiles", "updated_at"),
        AuthoringSchemaRequirement.Column("item_consumable_requirements", "item_id"),
        AuthoringSchemaRequirement.Column("item_consumable_requirements", "requirement_index"),
        AuthoringSchemaRequirement.Column("item_consumable_requirements", "requirement_type"),
        AuthoringSchemaRequirement.Column("item_consumable_requirements", "target_id"),
        AuthoringSchemaRequirement.Column("item_consumable_requirements", "minimum_value"),
        AuthoringSchemaRequirement.Column("item_consumable_effects", "item_id"),
        AuthoringSchemaRequirement.Column("item_consumable_effects", "effect_index"),
        AuthoringSchemaRequirement.Column("item_consumable_effects", "effect_type"),
        AuthoringSchemaRequirement.Column("item_consumable_effects", "target_id"),
        AuthoringSchemaRequirement.Column("item_consumable_effects", "minimum_amount"),
        AuthoringSchemaRequirement.Column("item_consumable_effects", "maximum_amount"),
        AuthoringSchemaRequirement.Column("item_skill_requirements", "item_id"),
        AuthoringSchemaRequirement.Column("item_skill_requirements", "skill_id"),
        AuthoringSchemaRequirement.Column("item_skill_requirements", "required_value"),
        AuthoringSchemaRequirement.Column("item_skill_modifiers", "item_id"),
        AuthoringSchemaRequirement.Column("item_skill_modifiers", "skill_id"),
        AuthoringSchemaRequirement.Column("item_skill_modifiers", "modifier_value"),
        AuthoringSchemaRequirement.Column("item_combat_profiles", "item_id"),
        AuthoringSchemaRequirement.Column("item_combat_profiles", "profile_id"),
        AuthoringSchemaRequirement.Column("item_combat_profiles", "attack_type"),
        AuthoringSchemaRequirement.Column("item_combat_profiles", "accuracy_style"),
        AuthoringSchemaRequirement.Column("item_combat_profiles", "minimum_range_tiles"),
        AuthoringSchemaRequirement.Column("item_combat_profiles", "maximum_range_tiles"),
        AuthoringSchemaRequirement.Column("item_combat_profiles", "attack_speed_units"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "attack_thrust"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "attack_slash"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "attack_crush"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "attack_ranged"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "attack_magic"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "strength_melee"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "strength_ranged"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "strength_magic"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "defence_thrust"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "defence_slash"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "defence_crush"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "defence_ranged"),
        AuthoringSchemaRequirement.Column("item_combat_bonuses", "defence_magic"),
        AuthoringSchemaRequirement.Column("item_tool_capabilities", "item_id"),
        AuthoringSchemaRequirement.Column("item_tool_capabilities", "capability_id"),
        AuthoringSchemaRequirement.Column("item_tool_capabilities", "capability_order"),
        AuthoringSchemaRequirement.Column("item_tool_capabilities", "power_tier"),
        AuthoringSchemaRequirement.Column("item_tool_capabilities", "action_animation_id"),
        AuthoringSchemaRequirement.Column("item_tool_capabilities", "effect_resource_id"),
        AuthoringSchemaRequirement.Column("item_equipped_visuals", "item_id"),
        AuthoringSchemaRequirement.Column("item_equipped_visuals", "asset_key"),
        AuthoringSchemaRequirement.Column("item_equipped_visuals", "rig_id"),
        AuthoringSchemaRequirement.Column("item_equipped_visuals", "binding_type"),
        AuthoringSchemaRequirement.Column("item_equipped_visuals", "render_layer_id"),
        AuthoringSchemaRequirement.Column("item_equipped_visuals", "socket_id"),
        AuthoringSchemaRequirement.Column("item_equipped_visuals", "secondary_socket_id"),
        AuthoringSchemaRequirement.Column("item_equipped_visuals", "nudge_x"),
        AuthoringSchemaRequirement.Column("item_equipped_visuals", "nudge_y"),
        AuthoringSchemaRequirement.Column("item_equipped_visual_pose_anchors", "item_id"),
        AuthoringSchemaRequirement.Column("item_equipped_visual_pose_anchors", "direction"),
        AuthoringSchemaRequirement.Column("item_equipped_visual_pose_anchors", "frame"),
        AuthoringSchemaRequirement.Column("item_equipped_visual_pose_anchors", "grip_anchor_x"),
        AuthoringSchemaRequirement.Column("item_equipped_visual_pose_anchors", "grip_anchor_y"),
        AuthoringSchemaRequirement.Column("item_equipped_visual_pose_anchors", "flip_x"),
        AuthoringSchemaRequirement.Column("item_equipped_visual_pose_anchors", "hidden"),
        AuthoringSchemaRequirement.Column("item_equipped_visual_pose_anchors", "item_over_grip"),
        AuthoringSchemaRequirement.Constraint("item_definitions_equipment_slot_id_fkey"),
        AuthoringSchemaRequirement.Constraint("item_definitions_reference_value_check"),
        AuthoringSchemaRequirement.Constraint("item_definitions_trade_policy_check"),
        AuthoringSchemaRequirement.Constraint("item_definitions_death_behavior_check"),
        AuthoringSchemaRequirement.Constraint("item_definitions_shop_price_policy_check"),
        AuthoringSchemaRequirement.Constraint("item_definitions_death_transform_policy_check"),
        AuthoringSchemaRequirement.Constraint("item_definitions_death_transform_item_id_fkey"),
        AuthoringSchemaRequirement.Constraint("item_definitions_death_reclaim_policy_check"),
        AuthoringSchemaRequirement.Constraint("item_consumable_profiles_use_action_check"),
        AuthoringSchemaRequirement.Constraint("item_consumable_profiles_consume_quantity_check"),
        AuthoringSchemaRequirement.Constraint("item_consumable_profiles_cooldown_ms_check"),
        AuthoringSchemaRequirement.Constraint("item_consumable_profiles_result_not_self_check"),
        AuthoringSchemaRequirement.Constraint("item_consumable_requirements_identity_key"),
        AuthoringSchemaRequirement.Constraint("item_consumable_requirements_index_check"),
        AuthoringSchemaRequirement.Constraint("item_consumable_requirements_type_check"),
        AuthoringSchemaRequirement.Constraint("item_consumable_requirements_skill_id_fkey"),
        AuthoringSchemaRequirement.Constraint("item_consumable_requirements_minimum_value_check"),
        AuthoringSchemaRequirement.Constraint("item_consumable_effects_identity_key"),
        AuthoringSchemaRequirement.Constraint("item_consumable_effects_index_check"),
        AuthoringSchemaRequirement.Constraint("item_consumable_effects_type_check"),
        AuthoringSchemaRequirement.Constraint("item_consumable_effects_resource_check"),
        AuthoringSchemaRequirement.Constraint("item_consumable_effects_amount_range_check"),
        AuthoringSchemaRequirement.Constraint("item_skill_requirements_required_value_check"),
        AuthoringSchemaRequirement.Constraint("item_combat_profiles_attack_type_check"),
        AuthoringSchemaRequirement.Constraint("item_combat_profiles_accuracy_style_check"),
        AuthoringSchemaRequirement.Constraint("item_combat_profiles_attack_type_accuracy_style_check"),
        AuthoringSchemaRequirement.Constraint("item_combat_profiles_attack_speed_units_check"),
        AuthoringSchemaRequirement.Constraint("item_tool_capabilities_pkey"),
        AuthoringSchemaRequirement.Constraint("item_tool_capabilities_item_id_fkey"),
        AuthoringSchemaRequirement.Constraint("item_tool_capabilities_capability_id_nonempty"),
        AuthoringSchemaRequirement.Constraint("item_tool_capabilities_order_check"),
        AuthoringSchemaRequirement.Constraint("item_tool_capabilities_power_tier_check"),
        AuthoringSchemaRequirement.Constraint("item_tool_capabilities_action_animation_id_nonempty"),
        AuthoringSchemaRequirement.Constraint("item_tool_capabilities_effect_resource_id_nonempty"),
        AuthoringSchemaRequirement.Constraint("item_tool_capabilities_item_order_key"),
        AuthoringSchemaRequirement.Constraint("item_equipped_visuals_asset_key_format_check"),
        AuthoringSchemaRequirement.Constraint("item_equipped_visuals_binding_type_check"),
        AuthoringSchemaRequirement.Constraint("item_equipped_visuals_socket_nonblank_check"),
        AuthoringSchemaRequirement.Constraint("item_equipped_visuals_secondary_socket_nonblank_check"),
        AuthoringSchemaRequirement.Constraint("item_equipped_visual_pose_anchors_pkey"),
        AuthoringSchemaRequirement.Constraint("item_equipped_visual_pose_anchors_direction_check"),
        AuthoringSchemaRequirement.Constraint("item_equipped_visual_pose_anchors_frame_check"),
        AuthoringSchemaRequirement.Trigger(
            "item_definitions",
            "item_definitions_runtime_disable_guard"),
        AuthoringSchemaRequirement.Trigger(
            "item_definitions",
            "item_definitions_runtime_economy_policy_guard"),
        AuthoringSchemaRequirement.Trigger(
            "item_definitions",
            "item_definitions_runtime_transform_target_delete_guard"),
        AuthoringSchemaRequirement.Trigger(
            "item_definitions",
            "item_definitions_consumable_result_publication_guard"),
        AuthoringSchemaRequirement.Trigger(
            "item_consumable_profiles",
            "item_consumable_profiles_result_publication_guard"),
        AuthoringSchemaRequirement.Trigger(
            "item_equipped_visuals",
            "item_equipped_visuals_touch_item_updated_at"),
        AuthoringSchemaRequirement.Trigger(
            "item_equipped_visual_pose_anchors",
            "item_equipped_visual_pose_anchors_touch_item_updated_at"),
        AuthoringSchemaRequirement.AbsentTrigger("item_tool_capabilities", "item_tool_capabilities_hand_slot_guard"),
        AuthoringSchemaRequirement.AbsentTrigger("item_definitions", "item_definitions_tool_capability_slot_guard")
    ];
}
