// Read-only Environment projections. Never serialize the desktop health DTO: it contains
// connection profile/database identities, filesystem paths and raw failure messages.
using MMO.ContentStudio.AuthoringHost.Contracts;
using MMO.ContentStudio.AuthoringHost.Services;
using static MMO.ContentStudio.AuthoringHost.Browser.BrowserJson;
namespace MMO.ContentStudio.AuthoringHost.Browser;

public static class BrowserEnvironment
{
    public static void MapBrowserEnvironment(this WebApplication app)
    {
        var routes = app.MapGroup("/studio/api/environment");
        routes.MapGet("/health", async (AuthoringHealthService service, CancellationToken ct) =>
        {
            var health = await service.CheckAsync(ct);
            return Json(new {
                checked_at_utc = DateTimeOffset.UtcNow,
                host_version = typeof(BrowserEnvironment).Assembly.GetName().Version?.ToString() ?? "Unknown",
                api_version = AuthoringApi.CurrentVersion,
                supported_api_versions = AuthoringApi.SupportedVersions,
                overall_status = health.OverallStatus,
                database_status = health.Database.Status,
                database_connected = health.Database.DatabaseName is not null,
                schema_verified = health.Database.Status == HealthState.Healthy,
                // IDs are generated by schema requirement providers, never database/error text.
                checks = health.Database.Checks.Select(check => new { id = check.Id, status = check.Status }),
                asset_roots = health.AssetRoots.Select((root, index) => new {
                    label = root.Id switch {
                        "game_client_assets" => "Game client assets",
                        "content_studio_workspace" => "Studio workspace",
                        "configuration" => "Asset root configuration",
                        _ => $"Additional asset root {index + 1}"
                    }, status = root.Status })
            });
        });
        routes.MapGet("/actor-assets", (ActorAppearanceCatalogService service) =>
        {
            var options = service.LoadOptions();
            return Json(new {
                rigs = new { available = options.RigsAvailable, count = options.Rigs.Count },
                calibrations = new { available = options.CalibrationsAvailable, count = options.Calibrations.Count },
                equipped_visuals = new { available = options.EquippedVisualsAvailable, count = options.EquippedVisuals.Count }
            });
        });
        // Call each authoring service directly. Desktop catalog providers can turn failed
        // reads into empty lists; a failed Environment read must never claim zero entries.
        routes.MapGet("/catalog/items", async (UnifiedItemAuthoringService service, CancellationToken ct) =>
            Summary(await service.ListAsync(null, ct), value => value.Items.Select(item => item.PublicationState)));
        routes.MapGet("/catalog/shops", async (ShopAuthoringService service, CancellationToken ct) =>
            Summary(await service.ListAsync(null, ct), value => value.Items.Select(item => item.PublicationState)));
        routes.MapGet("/catalog/loot-tables", async (LootTableAuthoringService service, CancellationToken ct) =>
            Summary(await service.ListAsync(null, ct), value => value.Items.Select(item => item.PublicationState)));
        routes.MapGet("/catalog/world-objects", async (WorldObjectAuthoringService service, CancellationToken ct) =>
            Summary(await service.ListAsync(null, ct), value => value.Items.Select(item => item.PublicationState)));
        routes.MapGet("/catalog/blacksmithing", async (BlacksmithingAuthoringService service, CancellationToken ct) =>
            Summary(await service.ListAsync(null, ct), value => value.Items.Select(item => item.PublicationState)));
        routes.MapGet("/catalog/quests", async (QuestAuthoringService service, CancellationToken ct) =>
            Summary(await service.ListAsync(null, ct), value => value.Items.Select(item => item.PublicationState)));
        routes.MapGet("/catalog/dialogue", async (DialogueAuthoringService service, CancellationToken ct) =>
            Summary(await service.ListAsync(null, ct), value => value.Items.Select(item => item.PublicationState)));
        routes.MapGet("/catalog/npcs", async (NpcAuthoringService service, CancellationToken ct) =>
            Summary(await service.ListAsync(null, ct), value => value.Items.Select(item => item.PublicationState)));
        routes.MapGet("/catalog/mobs", async (MobAuthoringService service, CancellationToken ct) =>
            Summary(await service.ListAsync(null, ct), value => value.Items.Select(item => item.PublicationState)));
        routes.MapGet("/catalog/spells", async (MagicSpellAuthoringService service, CancellationToken ct) =>
            Summary(await service.ListAsync(null, ct), value => value.Items.Select(item => item.PublicationState)));
    }

    private static IResult Summary<T>(AuthoringOperationResult<T> result, Func<T, IEnumerable<string>> states)
    {
        if (!result.Succeeded || result.Value is null)
            return Error("catalog_unavailable", "Catalog could not be read. Check database/schema status and retry.", 503);
        var values = states(result.Value).ToArray();
        return Json(new { count = values.Length,
            published = values.Count(value => value == "Published"),
            draft = values.Count(value => value == "Draft"),
            disabled = values.Count(value => value == "Disabled"),
            other = values.Count(value => value is not ("Published" or "Draft" or "Disabled")) });
    }
}
