using MMO.ContentStudio.AuthoringHost.Health;

namespace MMO.ContentStudio.AuthoringHost.Features.LootTables;

public sealed class LootTableSchemaRequirements : IAuthoringSchemaRequirementProvider
{
    public string FeatureId => "authored-rng-loot-tables-v1";

    public IReadOnlyList<AuthoringSchemaRequirement> GetRequirements() =>
    [
        AuthoringSchemaRequirement.Table("loot_tables"),
        AuthoringSchemaRequirement.Table("loot_table_roll_groups"),
        AuthoringSchemaRequirement.Table("loot_table_outcomes"),
        AuthoringSchemaRequirement.Table("item_definitions"),
        AuthoringSchemaRequirement.Table("mob_definitions"),
        AuthoringSchemaRequirement.Column("loot_tables", "loot_table_id"),
        AuthoringSchemaRequirement.Column("loot_tables", "display_name"),
        AuthoringSchemaRequirement.Column("loot_tables", "description"),
        AuthoringSchemaRequirement.Column("loot_tables", "publication_state"),
        AuthoringSchemaRequirement.Column("loot_tables", "content_fingerprint"),
        AuthoringSchemaRequirement.Column("loot_tables", "updated_at"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "created_at"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "loot_table_id"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "roll_group_id"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "section_kind"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "group_order"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "roll_kind"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "roll_count"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "pre_roll_failure_behavior"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "pre_roll_success_sequence_behavior"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "pre_roll_success_main_behavior"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "display_name"),
        AuthoringSchemaRequirement.Column("loot_table_roll_groups", "updated_at"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "loot_table_id"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "roll_group_id"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "outcome_id"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "outcome_order"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "outcome_kind"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "item_id"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "nested_loot_table_id"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "min_quantity"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "max_quantity"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "weight"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "probability_numerator"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "probability_denominator"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "created_at"),
        AuthoringSchemaRequirement.Column("loot_table_outcomes", "updated_at"),
        AuthoringSchemaRequirement.Column("item_definitions", "reference_value"),
        AuthoringSchemaRequirement.Column("item_definitions", "runtime_enabled"),
        AuthoringSchemaRequirement.Column("mob_definitions", "root_loot_table_id"),
        AuthoringSchemaRequirement.Constraint("loot_tables_id_format_check"),
        AuthoringSchemaRequirement.Constraint("loot_tables_display_name_check"),
        AuthoringSchemaRequirement.Constraint("loot_tables_publication_state_check"),
        AuthoringSchemaRequirement.Constraint("loot_tables_content_fingerprint_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_id_format_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_section_kind_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_order_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_roll_kind_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_roll_count_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_pre_roll_failure_behavior_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_pre_roll_shape_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_pre_roll_success_sequence_behavior_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_pre_roll_success_main_behavior_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_pre_roll_success_shape_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_guaranteed_shape_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_tertiary_shape_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_roll_groups_display_name_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_outcomes_id_format_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_outcomes_order_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_outcomes_kind_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_outcomes_weight_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_outcomes_quantity_shape_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_outcomes_probability_shape_check"),
        AuthoringSchemaRequirement.Constraint("loot_table_outcomes_kind_field_shape_check"),
        AuthoringSchemaRequirement.Constraint("mob_definitions_root_loot_table_id_fkey")
    ];
}
