-- Seed currently hard-coded runtime NPC definitions into reusable authoring rows.
-- This is a handoff artifact for MMO Project; Content Studio does not apply it
-- automatically and this file must not be treated as a runtime hot-reload path.

INSERT INTO npc_definitions (
    npc_definition_id,
    display_name,
    publication_state,
    visual_texture_path,
    source_width,
    source_height,
    visual_anchor_offset_x,
    visual_anchor_offset_y,
    visual_render_scale,
    footprint_width_tiles,
    footprint_height_tiles,
    movement_behavior,
    wander_radius_tiles,
    tick_interval_ms,
    idle_chance,
    interaction_enabled,
    interaction_range_tiles,
    default_interaction,
    default_dialogue_id,
    notes
) VALUES (
    'test_npc',
    'Test NPC',
    'Published',
    'res://assets/actors/npcs/Chars_139_200-F2-S.png',
    184,
    180,
    0,
    0,
    0.25,
    1,
    1,
    'static',
    0,
    600,
    0.15,
    TRUE,
    1,
    'talk',
    'test_npc_greeting',
    'Seeded from the pre-T5E hard-coded runtime NPC.'
)
ON CONFLICT (npc_definition_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    publication_state = EXCLUDED.publication_state,
    visual_texture_path = EXCLUDED.visual_texture_path,
    source_width = EXCLUDED.source_width,
    source_height = EXCLUDED.source_height,
    visual_anchor_offset_x = EXCLUDED.visual_anchor_offset_x,
    visual_anchor_offset_y = EXCLUDED.visual_anchor_offset_y,
    visual_render_scale = EXCLUDED.visual_render_scale,
    footprint_width_tiles = EXCLUDED.footprint_width_tiles,
    footprint_height_tiles = EXCLUDED.footprint_height_tiles,
    movement_behavior = EXCLUDED.movement_behavior,
    wander_radius_tiles = EXCLUDED.wander_radius_tiles,
    tick_interval_ms = EXCLUDED.tick_interval_ms,
    idle_chance = EXCLUDED.idle_chance,
    interaction_enabled = EXCLUDED.interaction_enabled,
    interaction_range_tiles = EXCLUDED.interaction_range_tiles,
    default_interaction = EXCLUDED.default_interaction,
    default_dialogue_id = EXCLUDED.default_dialogue_id,
    notes = EXCLUDED.notes,
    updated_at_utc = NOW();
