-- Burning terrain spell facts. No spell row or artwork is seeded.
BEGIN;
ALTER TABLE magic_combat_spells
    ADD COLUMN ignition_base_success_percent INTEGER NULL CONSTRAINT magic_spells_ignition_base_success_percent_check CHECK (ignition_base_success_percent IS NULL OR ignition_base_success_percent BETWEEN 0 AND 100),
    ADD COLUMN ignition_magic_levels_per_step INTEGER NULL CONSTRAINT magic_spells_ignition_magic_levels_per_step_check CHECK (ignition_magic_levels_per_step IS NULL OR ignition_magic_levels_per_step > 0),
    ADD COLUMN ignition_success_percent_per_step INTEGER NULL CONSTRAINT magic_spells_ignition_success_percent_per_step_check CHECK (ignition_success_percent_per_step IS NULL OR ignition_success_percent_per_step BETWEEN 0 AND 100),
    ADD COLUMN burning_lifetime_milliseconds INTEGER NULL CONSTRAINT magic_spells_burning_lifetime_milliseconds_check CHECK (burning_lifetime_milliseconds IS NULL OR burning_lifetime_milliseconds > 0),
    ADD COLUMN burning_capacity_magic_levels_per_step INTEGER NULL CONSTRAINT magic_spells_burning_capacity_magic_levels_per_step_check CHECK (burning_capacity_magic_levels_per_step IS NULL OR burning_capacity_magic_levels_per_step > 0),
    ADD COLUMN burning_max_active INTEGER NULL CONSTRAINT magic_spells_burning_max_active_check CHECK (burning_max_active IS NULL OR burning_max_active > 0),
    ADD COLUMN burning_min_damage INTEGER NULL CONSTRAINT magic_spells_burning_min_damage_check CHECK (burning_min_damage IS NULL OR burning_min_damage > 0),
    ADD COLUMN burning_max_damage INTEGER NULL CONSTRAINT magic_spells_burning_max_damage_check CHECK (burning_max_damage IS NULL OR burning_max_damage > 0),
    ADD COLUMN burning_hazard_cooldown_milliseconds INTEGER NULL CONSTRAINT magic_spells_burning_hazard_cooldown_milliseconds_check CHECK (burning_hazard_cooldown_milliseconds IS NULL OR burning_hazard_cooldown_milliseconds > 0),
    ADD COLUMN burning_visual_texture_path TEXT NULL CONSTRAINT magic_spells_burning_visual_texture_path_check CHECK (burning_visual_texture_path IS NULL OR (burning_visual_texture_path ~ '^res://assets/[^:]+\.png$' AND substring(burning_visual_texture_path from 14) !~ '(^|/)(\.\.?|)(/|$)' AND position(chr(92) in burning_visual_texture_path) = 0)),
    ADD COLUMN burning_visual_render_scale DOUBLE PRECISION NULL CONSTRAINT magic_spells_burning_visual_render_scale_check CHECK (burning_visual_render_scale IS NULL OR (burning_visual_render_scale > 0 AND burning_visual_render_scale < 'Infinity'::double precision)),
    ADD CONSTRAINT magic_spells_burning_damage_range_check CHECK (burning_min_damage IS NULL OR burning_max_damage IS NULL OR burning_max_damage >= burning_min_damage),
    DROP CONSTRAINT magic_spells_impact_effect_check,
    ADD CONSTRAINT magic_spells_impact_effect_check CHECK (impact_effect IS NULL OR impact_effect IN ('air_displacement', 'earth_matter', 'burning_terrain')),
    DROP CONSTRAINT magic_spells_force_shape_check,
    ADD CONSTRAINT magic_spells_force_shape_check CHECK ((impact_effect = 'air_displacement' AND force IS NOT NULL AND force_falloff_per_tile IS NOT NULL AND max_displacement_tiles IS NOT NULL) OR (COALESCE(impact_effect <> 'air_displacement', true) AND force IS NULL AND force_falloff_per_tile IS NULL AND max_displacement_tiles IS NULL)),
    ADD CONSTRAINT magic_spells_burning_shape_check CHECK (COALESCE(impact_effect = 'burning_terrain', false) OR (ignition_base_success_percent IS NULL AND ignition_magic_levels_per_step IS NULL AND ignition_success_percent_per_step IS NULL AND burning_lifetime_milliseconds IS NULL AND burning_capacity_magic_levels_per_step IS NULL AND burning_max_active IS NULL AND burning_min_damage IS NULL AND burning_max_damage IS NULL AND burning_hazard_cooldown_milliseconds IS NULL AND burning_visual_texture_path IS NULL AND burning_visual_render_scale IS NULL)),
    DROP CONSTRAINT magic_spells_published_shape_check,
    ADD CONSTRAINT magic_spells_published_shape_check CHECK (publication_state <> 'Published' OR COALESCE(
        (cast_mode = 'selected_combat' AND target_mode = 'mob' AND impact_effect IS NULL AND force IS NULL AND force_falloff_per_tile IS NULL AND max_displacement_tiles IS NULL AND manifestation_base_success_percent IS NULL AND manifestation_magic_levels_per_step IS NULL AND manifestation_success_percent_per_step IS NULL AND matter_lifetime_milliseconds IS NULL AND matter_capacity_magic_levels_per_step IS NULL AND matter_max_active IS NULL AND matter_visual_texture_path IS NULL AND matter_visual_render_scale IS NULL)
        OR (cast_mode = 'explicit_technique' AND target_mode = 'physical' AND element = 'air' AND impact_effect = 'air_displacement' AND successful_hit_min_damage = 0 AND base_max_hit = 0 AND manifestation_base_success_percent IS NULL AND manifestation_magic_levels_per_step IS NULL AND manifestation_success_percent_per_step IS NULL AND matter_lifetime_milliseconds IS NULL AND matter_capacity_magic_levels_per_step IS NULL AND matter_max_active IS NULL AND matter_visual_texture_path IS NULL AND matter_visual_render_scale IS NULL)
        OR (cast_mode = 'explicit_technique' AND target_mode = 'tile' AND element = 'earth' AND impact_effect = 'earth_matter' AND successful_hit_min_damage = 0 AND base_max_hit = 0 AND force IS NULL AND force_falloff_per_tile IS NULL AND max_displacement_tiles IS NULL AND manifestation_base_success_percent IS NOT NULL AND manifestation_magic_levels_per_step IS NOT NULL AND manifestation_success_percent_per_step IS NOT NULL AND matter_lifetime_milliseconds IS NOT NULL AND matter_capacity_magic_levels_per_step IS NOT NULL AND matter_max_active IS NOT NULL AND matter_physical_weight IS NOT NULL AND matter_visual_texture_path IS NOT NULL AND matter_visual_render_scale IS NOT NULL)
        OR (cast_mode = 'explicit_technique' AND target_mode = 'tile' AND element = 'fire' AND impact_effect = 'burning_terrain' AND successful_hit_min_damage = 0 AND base_max_hit = 0 AND force IS NULL AND force_falloff_per_tile IS NULL AND max_displacement_tiles IS NULL AND force_mastery_magic_levels_per_step IS NULL AND force_mastery_force_per_step IS NULL AND force_mastery_max_force IS NULL AND displacement_mastery_magic_levels_per_step IS NULL AND displacement_mastery_tiles_per_step IS NULL AND displacement_mastery_max_tiles IS NULL AND manifestation_base_success_percent IS NULL AND manifestation_magic_levels_per_step IS NULL AND manifestation_success_percent_per_step IS NULL AND matter_lifetime_milliseconds IS NULL AND matter_capacity_magic_levels_per_step IS NULL AND matter_max_active IS NULL AND matter_physical_weight IS NULL AND matter_visual_texture_path IS NULL AND matter_visual_render_scale IS NULL AND ignition_base_success_percent IS NOT NULL AND ignition_magic_levels_per_step IS NOT NULL AND ignition_success_percent_per_step IS NOT NULL AND burning_lifetime_milliseconds IS NOT NULL AND burning_capacity_magic_levels_per_step IS NOT NULL AND burning_max_active IS NOT NULL AND burning_min_damage IS NOT NULL AND burning_max_damage IS NOT NULL AND burning_hazard_cooldown_milliseconds IS NOT NULL AND burning_visual_texture_path IS NOT NULL AND burning_visual_render_scale IS NOT NULL), false));
INSERT INTO schema_migrations(migration_file, migration_number, migration_name, notes)
VALUES ('086_magic_kindle_burning_terrain.sql', 86, 'magic_kindle_burning_terrain', 'Authored Fire ignition, capacity, hazard and persistent visual facts; no spell content changes.');
COMMIT;
